# Generated by Django 5.1.4 on 2025-01-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('Singer', models.CharField(max_length=255)),
                ('is_listen', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
